In [43]:
import pandas as pd
import cohere
import os
from pathlib import Path
from cohere.classify import Example

In [44]:
current_dir = os.getcwd()
data_dir = os.getcwd() + '/data'

In [2]:
data = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRVDXp9du6jQpOUkH4m4fYsGNucevTw201YMQE9lJDcwokYWO9XeISVF1vPWq2jp2fSA5MTMqVpVCoU/pub?output=csv')
data.head()

,Answer,Answer.f1.afraid.raw,Answer.f1.angry.raw,Answer.f1.anxious.raw,Answer.f1.ashamed.raw,Answer.f1.awkward.raw,Answer.f1.bored.raw,Answer.f1.calm.raw,Answer.f1.confused.raw,Answer.f1.disgusted.raw,...,Answer.t1.family.raw,Answer.t1.food.raw,Answer.t1.friends.raw,Answer.t1.god.raw,Answer.t1.health.raw,Answer.t1.love.raw,Answer.t1.recreation.raw,Answer.t1.school.raw,Answer.t1.sleep.raw,Answer.t1.work.raw
0,"My family was the most salient part of my day,...",False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1,Yoga keeps me focused. I am able to take some ...,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,"Yesterday, my family and I played a bunch of b...",False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
3,"Yesterday, I visited my parents and had dinner...",False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
4,"Yesterday, I really felt the importance of my ...",False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [3]:
emotions_data = data.iloc[:,:19]
emotions_data.head()

,Answer,Answer.f1.afraid.raw,Answer.f1.angry.raw,Answer.f1.anxious.raw,Answer.f1.ashamed.raw,Answer.f1.awkward.raw,Answer.f1.bored.raw,Answer.f1.calm.raw,Answer.f1.confused.raw,Answer.f1.disgusted.raw,Answer.f1.excited.raw,Answer.f1.frustrated.raw,Answer.f1.happy.raw,Answer.f1.jealous.raw,Answer.f1.nostalgic.raw,Answer.f1.proud.raw,Answer.f1.sad.raw,Answer.f1.satisfied.raw,Answer.f1.surprised.raw
0,"My family was the most salient part of my day,...",False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
1,Yoga keeps me focused. I am able to take some ...,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,"Yesterday, my family and I played a bunch of b...",False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False
3,"Yesterday, I visited my parents and had dinner...",False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
4,"Yesterday, I really felt the importance of my ...",False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [4]:
text = emotions_data.iloc[:,:1]
labels = emotions_data.iloc[:,1:]
labels.head()

,Answer.f1.afraid.raw,Answer.f1.angry.raw,Answer.f1.anxious.raw,Answer.f1.ashamed.raw,Answer.f1.awkward.raw,Answer.f1.bored.raw,Answer.f1.calm.raw,Answer.f1.confused.raw,Answer.f1.disgusted.raw,Answer.f1.excited.raw,Answer.f1.frustrated.raw,Answer.f1.happy.raw,Answer.f1.jealous.raw,Answer.f1.nostalgic.raw,Answer.f1.proud.raw,Answer.f1.sad.raw,Answer.f1.satisfied.raw,Answer.f1.surprised.raw
0,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False
3,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [5]:
labels = labels.astype(int)
labels.head()

,Answer.f1.afraid.raw,Answer.f1.angry.raw,Answer.f1.anxious.raw,Answer.f1.ashamed.raw,Answer.f1.awkward.raw,Answer.f1.bored.raw,Answer.f1.calm.raw,Answer.f1.confused.raw,Answer.f1.disgusted.raw,Answer.f1.excited.raw,Answer.f1.frustrated.raw,Answer.f1.happy.raw,Answer.f1.jealous.raw,Answer.f1.nostalgic.raw,Answer.f1.proud.raw,Answer.f1.sad.raw,Answer.f1.satisfied.raw,Answer.f1.surprised.raw
0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
3,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [6]:
labels = labels.rename(columns={'Answer.f1.afraid.raw': "Afraid", 
                       "Answer.f1.angry.raw": "Angry", 
                       "Answer.f1.anxious.raw": "Anxious",
                       "Answer.f1.ashamed.raw": "Ashamed",
                       "Answer.f1.awkward.raw": "Awkward",
                       "Answer.f1.bored.raw": "Bored",
                       "Answer.f1.calm.raw": "Calm",
                       "Answer.f1.confused.raw": "Confused",
                       "Answer.f1.disgusted.raw": "Disgusted",
                       "Answer.f1.excited.raw": "Excited",
                       "Answer.f1.frustrated.raw": "Frustrated",
                       "Answer.f1.happy.raw": "Happy",
                       "Answer.f1.jealous.raw": "Jealous",
                       "Answer.f1.nostalgic.raw": "Nostalgic",
                       "Answer.f1.proud.raw": "Proud",
                       "Answer.f1.sad.raw": "Sad",
                       "Answer.f1.satisfied.raw": "Satisfied",
                       "Answer.f1.surprised.raw": "Surprised",})

In [15]:
labels

,Afraid,Angry,Anxious,Ashamed,Awkward,Bored,Calm,Confused,Disgusted,Excited,Frustrated,Happy,Jealous,Nostalgic,Proud,Sad,Satisfied,Surprised
0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
3,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1469,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
1470,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
1471,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1472,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0

In [33]:
labels.columns
desired_emotions = ['Afraid', 'Angry', 'Anxious', 'Calm',
       'Confused', 'Excited', 'Frustrated', 'Happy', 'Jealous',
       'Nostalgic', 'Proud', 'Sad', 'Satisfied']
# take away ashamed, awkward, bored, disgusted, surprised

In [30]:
emotions = {}
for i in range(len(labels.columns)):
    emotions[labels.columns[i]] = labels.iloc[:,i]

In [34]:
filtered_emotions = {}
for emotion in desired_emotions:
    filtered_emotions[emotion] = emotions[emotion]

In [35]:
filtered_emotions

{'Afraid': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Afraid, Length: 1473, dtype: int64,
 'Angry': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Angry, Length: 1473, dtype: int64,
 'Anxious': 0       1
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Anxious, Length: 1473, dtype: int64,
 'Calm': 0       0
 1       1
 2       1
 3       1
 4       0
        ..
 1468    0
 1469    1
 1470    0
 1471    0
 1472    1
 Name: Calm, Length: 1473, dtype: int64,
 'Confused': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Confused, Length: 1473, dtype: int64,
 'Excited': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Excited, Length: 1473, dtype: int64,
 'Frustrated': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Frustrated, Length: 1473, dtype: int64,
 'Happy': 0       1
 1       0
 2       1
 3       1
 4       1
        ..
 1468    1
 1469    1
 1470    1
 1471    1
 1472    0
 Name: Happy, Length: 1473, dtype: int64,
 'Jealous': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Jealous, Length: 1473, dtype: int64,
 'Nostalgic': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Nostalgic, Length: 1473, dtype: int64,
 'Proud': 0       1
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    1
 1471    0
 1472    0
 Name: Proud, Length: 1473, dtype: int64,
 'Sad': 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1468    0
 1469    0
 1470    0
 1471    0
 1472    0
 Name: Sad, Length: 1473, dtype: int64,
 'Satisfied': 0       0
 1       0
 2       1
 3       0
 4       0
        ..
 1468    1
 1469    0
 1470    0
 1471    0
 1472    1
 Name: Satisfied, Length: 1473, dtype: int64}

In [39]:
test = pd.merge(text, filtered_emotions['Afraid'], right_index = True, left_index = True)
test

                                                 Answer  Afraid
0     My family was the most salient part of my day,...       0
1     Yoga keeps me focused. I am able to take some ...       0
2     Yesterday, my family and I played a bunch of b...       0
3     Yesterday, I visited my parents and had dinner...       0
4     Yesterday, I really felt the importance of my ...       0
...                                                 ...     ...
1468  A workout, dining with friends makes for a hea...       0
1469  My connection to God, through prayer brings me...       0
1470  I got a skull pan for halloween, and my husban...       0
1471  I spoke over the phone with my brother that li...       0
1472  I had a lengthy but mostly fun, frivolous conv...       0

[1473 rows x 2 columns]

In [ ]:
df_emotions = []
for emotion in desired_emotions:
    test = pd.merge(text, filtered_emotions[emotion], right_index = True, left_index = True)
    filepath = Path('folder/subfolder/out.csv')
    test.to_csv(current_dir + emotion + '.csv')

In [ ]:
all_in_one_multi_label_model(input_text) -> [0, 1, 1, 0]


model_for_label_1(input_text) -> 0 or 1
model_for_label_1(input_text) -> 0 or 1
model_for_label_1(input_text) -> 0 or 1
model_for_label_1(input_text) -> 0 or 1

[0, 1, 1, 0]